// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwuazurgrxvjsxrhdkwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3dWF6dXJncnh2anN4cmhka3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTMyNDYsImV4cCI6MjA2ODg4OTI0Nn0.EOykmFUlrfkcxQM8EAvOwTP5T_BizuIuX4ByYV4u4G4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});